'use client';
import React, { useState } from 'react';
import { Box, Chip } from '@mui/material';
import { useTranslations } from 'next-intl';

export default function TagsBar({ tags, handleSearch }: { tags: (string | undefined)[], handleSearch: (tags: string[]) => void}) {
    const t = useTranslations('Tags');
    const [selected, setSelected] = useState<string[]>([]);

    const handleClick = (tag: string) => {
        const selectedIndex = selected.indexOf(tag);
        let newSelected: string[] = [];

        if (selectedIndex === -1) {
            newSelected = newSelected.concat(selected, tag);
        } else if (selectedIndex === 0) {
            newSelected = newSelected.concat(selected.slice(1));
        } else if (selectedIndex === selected.length - 1) {
            newSelected = newSelected.concat(selected.slice(0, -1));
        } else if (selectedIndex > 0) {
            newSelected = newSelected.concat(
                selected.slice(0, selectedIndex),
                selected.slice(selectedIndex + 1),
            );
        }

        handleSearch(newSelected);
        setSelected(newSelected);
    }; //Generated by copilot

    return (
        <Box
            sx={{
                display: 'flex',
                flexWrap: 'wrap',
                gap: '0.5rem',
            }}
        >
            {tags.length === 0 && t('no-tags')}
            {tags.map((tag) => (
                tag &&
                <Chip
                    key={tag}
                    label={t(tag)}
                    variant="filled"
                    color={selected.indexOf(tag) !== -1 ? 'primary' : 'default'}
                    sx={{
                        borderRadius: '8px',
                    }}
                    onClick={() => handleClick(tag)}
                />
            ))}
        </Box>
    );
}